# defaults file for mindx.basic
DL_USR: "{{ MINDX_USER }}"
DL_GRP: "{{ MINDX_GROUP }}"
DL_UID: "{{ MINDX_USER_ID }}"
DL_GID: "{{ MINDX_GROUP_ID }}"

resource_dir: "~/resources"
OS_ID: "{{ lookup('ini', 'ID type=properties section=global file=/etc/os-release') | replace('\"', '') }}"
OS_VERSION_ID: "{{ lookup('ini', 'VERSION_ID type=properties section=global file=/etc/os-release') | replace('\"', '') }}"

haveged_dir: "{{resource_dir}}/{{OS_ID}}_{{OS_VERSION_ID}}_{{ansible_architecture}}/haveged"
