# Copyright Â© Huawei Technologies Co., Ltd. 2020. All rights reserved.
---
- hosts: localnode, master
  remote_user: root

  tasks:
    - name: Pull kubernetes basic images - arm64
      shell:
        cmd:
          docker pull {{ item }}
      with_items:
        - cruse/kube-apiserver-arm64:v1.17.3
        - cruse/kube-controller-manager-arm64:v1.17.3
        - cruse/kube-scheduler-arm64:v1.17.3-beta.0
        - cruse/kube-proxy-arm64:v1.17.3-beta.0
        - cruse/pause-arm64:3.1
        - cruse/etcd-arm64:3.4.3-0
        - coredns/coredns:1.6.5
        - calico/node:v3.11.3
        - calico/pod2daemon-flexvol:v3.11.3
        - calico/cni:v3.11.3
        - calico/kube-controllers:v3.11.3
      when: ansible_architecture == "aarch64"
      tags:
        - kubernetes_basic

    - name: Pull kubernetes basic images - x86_64
      shell:
        cmd:
          docker pull {{ item }}
      with_items:
        - kubesphere/kube-apiserver:v1.17.3
        - kubesphere/kube-controller-manager:v1.17.3
        - kubesphere/kube-scheduler:v1.17.3
        - kubesphere/kube-proxy:v1.17.3
        - kubesphere/pause:3.1
        - cruse/etcd-amd64:3.4.3-0
        - coredns/coredns:1.6.5
        - calico/node:v3.11.3
        - calico/pod2daemon-flexvol:v3.11.3
        - calico/cni:v3.11.3
        - calico/kube-controllers:v3.11.3
      when: ansible_architecture == "x86_64"
      tags:
        - kubernetes_basic

    - name: Tag images - arm64
      shell:
        cmd:
          docker tag {{ item }}
      with_items:
        - cruse/kube-apiserver-arm64:v1.17.3 k8s.gcr.io/kube-apiserver:v1.17.3
        - cruse/kube-controller-manager-arm64:v1.17.3 k8s.gcr.io/kube-controller-manager:v1.17.3
        - cruse/kube-scheduler-arm64:v1.17.3-beta.0 k8s.gcr.io/kube-scheduler:v1.17.3
        - cruse/kube-proxy-arm64:v1.17.3-beta.0 k8s.gcr.io/kube-proxy:v1.17.3
        - cruse/pause-arm64:3.1 k8s.gcr.io/pause:3.1
        - cruse/etcd-arm64:3.4.3-0 k8s.gcr.io/etcd:3.4.3-0
        - coredns/coredns:1.6.5 k8s.gcr.io/coredns:1.6.5
      when: ansible_architecture == "aarch64"
      tags:
        - kubernetes_basic

    - name: Tag images - x86_64
      shell:
        cmd:
          docker tag {{ item }}
      with_items:
        - kubesphere/kube-apiserver:v1.17.3 k8s.gcr.io/kube-apiserver:v1.17.3
        - kubesphere/kube-controller-manager:v1.17.3 k8s.gcr.io/kube-controller-manager:v1.17.3
        - kubesphere/kube-scheduler:v1.17.3 k8s.gcr.io/kube-scheduler:v1.17.3
        - kubesphere/kube-proxy:v1.17.3 k8s.gcr.io/kube-proxy:v1.17.3
        - kubesphere/pause:3.1 k8s.gcr.io/pause:3.1
        - cruse/etcd-amd64:3.4.3-0 k8s.gcr.io/etcd:3.4.3-0
        - coredns/coredns:1.6.5 k8s.gcr.io/coredns:1.6.5
      when: ansible_architecture == "x86_64"
      tags:
        - kubernetes_basic

    # =========================== Use ascend-hub =============================
    - name: Ascend-hub docker login
      shell:
        cmd:
          "{{ ascendhub_login_command }}"
      tags:
        - basic_only

    - name: Pull mindx images - arm64
      shell:
        cmd:
          docker pull {{ ascend_hub_prefix }}/{{ item }}
      with_items:
        - vc-controller-manager_arm64:{{ volcano_version }}
        - vc-scheduler_arm64:{{ volcano_version }}
        - vc-webhook-manager_arm64:{{ volcano_version }}
        - vc-webhook-manager-base_arm64:{{ volcano_version }}
        - hccl-controller_arm64:{{ hccl_version }}
      when: ansible_architecture == "aarch64"
      tags:
        - basic_only

    - name: Pull mindx images - x86_64
      shell:
        cmd:
          docker pull {{ ascend_hub_prefix }}/{{ item }}
      with_items:
        - vc-controller-manager_amd64:{{ volcano_version }}
        - vc-scheduler_amd64:{{ volcano_version }}
        - vc-webhook-manager_amd64:{{ volcano_version }}
        - vc-webhook-manager-base_amd64:{{ volcano_version }}
        - hccl-controller_amd64:{{ hccl_version }}
      when: ansible_architecture == "x86_64"
      tags:
        - basic_only

    - name: Tag mindx images - arm64
      shell:
        cmd:
          docker tag {{ ascend_hub_prefix }}/{{ item }}
      with_items:
        - vc-controller-manager_arm64:{{ volcano_version }} volcanosh/vc-controller-manager:{{ volcano_version }}
        - vc-scheduler_arm64:{{ volcano_version }} volcanosh/vc-scheduler:{{ volcano_version }}
        - vc-webhook-manager_arm64:{{ volcano_version }} volcanosh/vc-webhook-manager:{{ volcano_version }}
        - vc-webhook-manager-base_arm64:{{ volcano_version }} volcanosh/vc-webhook-manager-base:{{ volcano_version }}
        - hccl-controller_arm64:{{ hccl_version }} hccl-controller:{{ hccl_version }}
      when: ansible_architecture == "aarch64"
      tags:
        - basic_only

    - name: Tag mindx images - x86_64
      shell:
        cmd:
          docker tag {{ ascend_hub_prefix }}/{{ item }}
      with_items:
        - vc-controller-manager_amd64:{{ volcano_version }} volcanosh/vc-controller-manager:{{ volcano_version }}
        - vc-scheduler_amd64:{{ volcano_version }} volcanosh/vc-scheduler:{{ volcano_version }}
        - vc-webhook-manager_amd64:{{ volcano_version }} volcanosh/vc-webhook-manager:{{ volcano_version }}
        - vc-webhook-manager-base_amd64:{{ volcano_version }} volcanosh/vc-webhook-manager-base:{{ volcano_version }}
        - hccl-controller_amd64:{{ hccl_version }} hccl-controller:{{ hccl_version }}
      when: ansible_architecture == "x86_64"
      tags:
        - basic_only
    # ========================================================================

# Pull k8s base images on worker
- hosts: workers
  remote_user: root

  tasks:
    - name: Workers pull kubernetes basic images - arm64
      shell:
        cmd:
          docker pull {{ item }}
      with_items:
        - cruse/kube-proxy-arm64:v1.17.3-beta.0
        - cruse/pause-arm64:3.1
        - calico/node:v3.11.3
        - calico/pod2daemon-flexvol:v3.11.3
        - calico/cni:v3.11.3
        - calico/kube-controllers:v3.11.3
      when:
        - ansible_architecture == "aarch64"
        - ansible_default_ipv4['address'] != master_ip
      tags:
        - kubernetes_basic

    - name: Workers pull kubernetes basic images - x86_64
      shell:
        cmd:
          docker pull {{ item }}
      with_items:
        - kubesphere/kube-proxy:v1.17.3
        - kubesphere/pause:3.1
        - calico/node:v3.11.3
        - calico/pod2daemon-flexvol:v3.11.3
        - calico/cni:v3.11.3
        - calico/kube-controllers:v3.11.3
      when:
        - ansible_architecture == "x86_64"
        - ansible_default_ipv4['address'] != master_ip
      tags:
        - kubernetes_basic

    - name: Workers tag images - arm64
      shell:
        cmd:
          docker tag {{ item }}
      with_items:
        - cruse/kube-proxy-arm64:v1.17.3-beta.0 k8s.gcr.io/kube-proxy:v1.17.3
        - cruse/pause-arm64:3.1 k8s.gcr.io/pause:3.1
      when:
        - ansible_architecture == "aarch64"
        - ansible_default_ipv4['address'] != master_ip
      tags:
        - kubernetes_basic

    - name: Workers tag images - x86_64
      shell:
        cmd:
          docker tag {{ item }}
      with_items:
        - kubesphere/kube-proxy:v1.17.3 k8s.gcr.io/kube-proxy:v1.17.3
        - kubesphere/pause:3.1 k8s.gcr.io/pause:3.1
      when:
        - ansible_architecture == "x86_64"
        - ansible_default_ipv4['address'] != master_ip
      tags:
        - kubernetes_basic

# Pull MindX DL images on worker
- hosts: localnode, workers
  remote_user: root

  tasks:
    - name: Ascend-hub docker login
      shell:
        cmd:
          "{{ ascendhub_login_command }}"
      tags:
        - basic_only

    - name: Pull mindx images - arm64
      shell:
        cmd:
          docker pull {{ ascend_hub_prefix }}/{{ item }}
      with_items:
        - ascend-k8sdeviceplugin_arm64:{{ deviceplugin_version }}
        - cadvisor_arm64:{{ cadvisor_version }}
      when: ansible_architecture == "aarch64"
      tags:
        - basic_only

    - name: Pull mindx images - x86_64
      shell:
        cmd:
          docker pull {{ ascend_hub_prefix }}/{{ item }}
      with_items:
        - ascend-k8sdeviceplugin_amd64:{{ deviceplugin_version }}
        - cadvisor_amd64:{{ cadvisor_version }}
      when: ansible_architecture == "x86_64"
      tags:
        - basic_only

    - name: Tag mindx images - arm64
      shell:
        cmd:
          docker tag {{ ascend_hub_prefix }}/{{ item }}
      with_items:
        - ascend-k8sdeviceplugin_arm64:{{ deviceplugin_version }} ascend-k8sdeviceplugin:{{ deviceplugin_version }}
        - cadvisor_arm64:{{ cadvisor_version }} google/cadvisor:{{ cadvisor_version }}
      when: ansible_architecture == "aarch64"
      tags:
        - basic_only

    - name: Tag mindx images - x86_64
      shell:
        cmd:
          docker tag {{ ascend_hub_prefix }}/{{ item }}
      with_items:
        - ascend-k8sdeviceplugin_amd64:{{ deviceplugin_version }} ascend-k8sdeviceplugin:{{ deviceplugin_version }}
        - cadvisor_amd64:{{ cadvisor_version }} google/cadvisor:{{ cadvisor_version }}
      when: ansible_architecture == "x86_64"
      tags:
        - basic_only

- hosts: localnode, master
  remote_user: root

  tasks:
    - name: Remove redundant images - arm64
      shell:
        cmd:
          docker rmi {{ item }}
      with_items:
        - cruse/kube-apiserver-arm64:v1.17.3
        - cruse/kube-controller-manager-arm64:v1.17.3
        - cruse/kube-scheduler-arm64:v1.17.3-beta.0
        - cruse/kube-proxy-arm64:v1.17.3-beta.0
        - cruse/pause-arm64:3.1
        - cruse/etcd-arm64:3.4.3-0
        - coredns/coredns:1.6.5
        - "{{ ascend_hub_prefix }}/vc-controller-manager_arm64:{{ volcano_version }}"
        - "{{ ascend_hub_prefix }}/vc-scheduler_arm64:{{ volcano_version }}"
        - "{{ ascend_hub_prefix }}/vc-webhook-manager_arm64:{{ volcano_version }}"
        - "{{ ascend_hub_prefix }}/vc-webhook-manager-base_arm64:{{ volcano_version }}"
        - "{{ ascend_hub_prefix }}/hccl-controller_arm64:{{ hccl_version }}"
      when: ansible_architecture == "aarch64"
      tags: always
      ignore_errors: yes

    - name: Remove redundant images - x86_64
      shell:
        cmd:
          docker rmi {{ item }}
      with_items:
        - kubesphere/kube-apiserver:v1.17.3
        - kubesphere/kube-controller-manager:v1.17.3
        - kubesphere/kube-scheduler:v1.17.3
        - kubesphere/kube-proxy:v1.17.3
        - kubesphere/pause:3.1
        - cruse/etcd-amd64:3.4.3-0
        - coredns/coredns:1.6.5
        - "{{ ascend_hub_prefix }}/vc-controller-manager_amd64:{{ volcano_version }}"
        - "{{ ascend_hub_prefix }}/vc-scheduler_amd64:{{ volcano_version }}"
        - "{{ ascend_hub_prefix }}/vc-webhook-manager_amd64:{{ volcano_version }}"
        - "{{ ascend_hub_prefix }}/vc-webhook-manager-base_amd64:{{ volcano_version }}"
        - "{{ ascend_hub_prefix }}/hccl-controller_amd64:{{ hccl_version }}"
      when: ansible_architecture == "x86_64"
      tags: always
      ignore_errors: yes

- hosts: localnode, workers
  remote_user: root

  tasks:
    - name: Workers remove redundant images - arm64
      shell:
        cmd:
          docker rmi {{ item }}
      with_items:
        - cruse/kube-proxy-arm64:v1.17.3-beta.0
        - cruse/pause-arm64:3.1
        - "{{ ascend_hub_prefix }}/ascend-k8sdeviceplugin_arm64:{{ deviceplugin_version }}"
        - "{{ ascend_hub_prefix }}/cadvisor_arm64:{{ cadvisor_version }}"
      when: ansible_architecture == "aarch64"
      tags: always
      ignore_errors: yes

    - name: Workers remove redundant images - x86_64
      shell:
        cmd:
          docker rmi {{ item }}
      with_items:
        - kubesphere/kube-proxy:v1.17.3
        - kubesphere/pause:3.1
        - "{{ ascend_hub_prefix }}/ascend-k8sdeviceplugin_amd64:{{ deviceplugin_version }}"
        - "{{ ascend_hub_prefix }}/cadvisor_amd64:{{ cadvisor_version }}"
      when: ansible_architecture == "x86_64"
      tags: always
      ignore_errors: yes

