---
- hosts:
    - harbor
    - master
  tasks:
  - name: set HARBOR_IP
    include_tasks: task_set_harbor_ip.yaml

# push inner-images to harbor
- hosts: master
  gather_facts: False
  roles:
    - role: mindx.harbor.push
      vars:
        project_list:
          - mindx
        project_public: "false"
        images_dir: mindx-inner-images
